SpecialtySelector/SpecialtySelector/Models/SubDepartment/AllSubDepartments.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpecialtySelector.Models.SubDepartment
{
    public class AllSubDepartments
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Името трябва да бъде между 3-1000 символа !!!")]
        [MaxLength(1000)]
        [MinLength(1)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Описанието трябва да бъде между 20-1600 символа !!!")]
        [StringLength(1600)]
        [MinLength(1)]
        public string Description { get; set; }

        public string AdminId { get; set; }

        public DateTime? DeletedOn { get; set; }

        public int? DepartmentId { get; set; }

        public string DepatrmentName { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/SubDepartment/CreateSubDepartment.cs
using System.ComponentModel.DataAnnotations;

namespace SpecialtySelector.Models.SubDepartment
{
    public class CreateSubDepartment
    {
        [Required(ErrorMessage = "Името трябва да бъде между 1-1000 символа !!!")]
        [Display(Name = "Име на Направлението")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Описанието трябва да бъде между 1-1600 символа !!!")]
        [Display(Name = "Кратко описание на Направлението")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Избери направление")]
        public int? DepartmentId { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/SubDepartment/SubDepartmentInfo.cs
using System.ComponentModel.DataAnnotations;

namespace SpecialtySelector.Models.SubDepartment
{
    public class SubDepartmentInfo
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(1000)]
        [MinLength(3)]
        public string Name { get; set; }

        [StringLength(1600)]
        public string Description { get; set; }

        public int? DepartmentId { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/SubDepartment/UpdateSubDepartment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpecialtySelector.Models.SubDepartment
{
    public class UpdateSubDepartment
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Името трябва да бъде между 3-1000 символа !!!")]
        [MaxLength(1000)]
        [MinLength(1)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Описанието трябва да бъде между 20-1600 символа !!!")]
        [StringLength(1600)]
        [MinLength(1)]
        public string Description { get; set; }

        public string AdminId { get; set; }

        public DateTime? DeletedOn { get; set; }

        public int? DepartmentId { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Controllers/SubDepartmentController.cs
using Microsoft.AspNet.Identity;
using SpecialtySelector.Data;
using SpecialtySelector.Models.SubDepartment;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace SpecialtySelector.Controllers
{
    public class SubDepartmentController : Controller
    {
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            using (var db = new SpecialtySelectorDbContext())
            {
                var departments = db.Departments.ToList();

                ViewBag.Departments = departments;

                return View();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateSubDepartment subDepartmentModel)
        {
            if (this.ModelState.IsValid && subDepartmentModel.Description != null && subDepartmentModel.Name != null)
            {
                var adminId = this.User.Identity.GetUserId();

                var subDepartment = new SubDepartment()
                {
                    Name = subDepartmentModel.Name,
                    Description = subDepartmentModel.Description,
                    DepartmentId = subDepartmentModel.DepartmentId,
                    AdminId = adminId
                };

                using (var db = new SpecialtySelectorDbContext())
                {
                    db.SubDepartments.Add(subDepartment);
                    db.SaveChanges();

                    return RedirectToAction("Details", new { id = subDepartment.Id });
                }
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var departments = db.Departments.ToList();

                ViewBag.Departments = departments;

                return View(subDepartmentModel);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subDepartment = db.SubDepartments
                    .Where(d => d.DeletedOn.Equals(null))
                    .Where(d => d.Id == id)
                    .Select(d => new SubDepartmentInfo()
                    {
                        Id = d.Id,
                        Name = d.Name,
                        Description = d.Description
                    })
                    .FirstOrDefault();

                if (subDepartment == null)
                {
                    return HttpNotFound();
                }

                return View(subDepartment);
            }
        }

        public ActionResult SubDepartmentInfo(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subDepartments = db.SubDepartments
                    .Where(sb => sb.DepartmentId == id)
                    .Where(sb => sb.DeletedOn.Equals(null))
                    .Select(sb => new SubDepartmentInfo()
                    {
                        Id = sb.Id,
                        Name = sb.Name,
                        Description = sb.Description
                    })
                    .ToList();

                if (subDepartments == null)
                {
                    return HttpNotFound();
                }

                return View(subDepartments);
            }
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                SubDepartment subDepartment = db.SubDepartments.FirstOrDefault(x => x.Id == id);

                if (subDepartment != null)
                {
                    subDepartment.DeletedOn = DateTime.Now;
                }

                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subDepartment = db.SubDepartments
                    .Find(id);

                if (subDepartment == null)
                {
                    return HttpNotFound();
                }

                var subDepartmentViewModel = new UpdateSubDepartment
                {
                    Id = subDepartment.Id,
                    Name = subDepartment.Name,
                    Description = subDepartment.Description,
                    AdminId = subDepartment.AdminId,
                    DepartmentId = subDepartment.DepartmentId
                };

                return View(subDepartmentViewModel);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Update(UpdateSubDepartment updateSubDepartment)
        {
            if (ModelState.IsValid)
            {
                using (var db = new SpecialtySelectorDbContext())
                {
                    var subDepartment = db.SubDepartments
                        .Find(updateSubDepartment.Id);

                    subDepartment.Name = updateSubDepartment.Name;
                    subDepartment.Description = updateSubDepartment.Description;
                    subDepartment.DeletedOn = updateSubDepartment.DeletedOn;
                    subDepartment.DepartmentId = updateSubDepartment.DepartmentId;
                    db.SaveChanges();
                }

                return RedirectToAction("Details", new { id = updateSubDepartment.Id });
            }

            return View(updateSubDepartment);
        }

        public ActionResult AllSubDepartments()
        {
            using (var db = new SpecialtySelectorDbContext())
            {
                var subDepartments = db.SubDepartments
                    .Include(x => x.Department.Name)
                    .Where(x => x.DeletedOn.Equals(null))
                    .Select(sp => new AllSubDepartments()
                    {
                        Id = sp.Id,
                        Name = sp.Name,
                        Description = sp.Description,
                        DepartmentId = sp.DepartmentId,
                        DepatrmentName = sp.Department.Name
                    })
                    .ToList();

                if (subDepartments == null)
                {
                    return HttpNotFound();
                }

                return View(subDepartments);
            }
        }
    }
}

SpecialtySelector/SpecialtySelector/Views/SubDepartment/AllSubDepartments.cshtml
@model IEnumerable<SpecialtySelector.Models.SubDepartment.AllSubDepartments>

@foreach (var s in Model)
{
    <div class="jumbotron text-center">
        <h2 class="lead text-info">
            Име на направлението: @s.DepatrmentName
        </h2>
        <h3 class="lead">
            Име на поднаправлението: @s.Name
        </h3>
        <div>
            <div class="lead">@s.Description</div>
        </div>
        @{if (Request.IsAuthenticated)
            {
                <div class="row">
                    <div class="col-md-6 text-right">
                        @using (Html.BeginForm("Delete", "SubDepartment", new { Id = s.Id }, FormMethod.Post))
                        {
                            <input class="btn btn-danger" type="submit" value="Изтриване" />
                        }
                    </div>
                    <div class="col-md-6 text-left">
                        @using (Html.BeginForm("Update", "SubDepartment", new { Id = s.Id }, FormMethod.Get))
                        {
                            <input class="btn btn-success" type="submit" value="Редактирай" />
                        }
                    </div>

                </div>
            }
        }
    </div>
    <hr />
            }

SpecialtySelector/SpecialtySelector/Views/SubDepartment/Create.cshtml
@model SpecialtySelector.Models.SubDepartment.CreateSubDepartment

@{
    ViewBag.Title = "Add Sub Department";
}

@using (Html.BeginForm("Create", "SubDepartment", FormMethod.Post))
{
    <div class="row text-center">
        <p class="lead">Име на поднаправлението:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Name, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name, new { style = "width:500px;" })
        </div>
        <p class="lead">Описание на поднарпавлението:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Description, "", new { style = "color:red" })
        </div>
        <div>
            @Html.TextAreaFor(m => m.Description, new { rows = "10", cols = "1200" })
        </div>
        <p class="lead">Връзка с направление :</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.DepartmentId, "", new { style = "color:red" })
        </div>
        <div>
            @{
                var departmentsList = new HashSet<SelectListItem>();
                foreach (var d in ViewBag.Departments)
                {
                    departmentsList.Add(new SelectListItem { Text = string.Format((string)"{0}", (object)d.Name), Value = string.Format((string)"{0}", (object)d.Id), Selected = false });
                }
            }
            @Html.DropDownListFor(m => m.DepartmentId, departmentsList)
        </div>
        <div>
            <input type="submit" value="Добави Поднаправление" />
        </div>
    </div>
}

SpecialtySelector/SpecialtySelector/Views/SubDepartment/Details.cshtml
@model SpecialtySelector.Models.SubDepartment.SubDepartmentInfo

@{
    ViewBag.Title = "Детайли";
}
<div class="jumbotron text-center lead">
    <div style="word-wrap: break-word">
        <h1>@Model.Name</h1>
    </div>
    <div style="word-wrap: break-word">
        <p class="lead">@Model.Description</p>
    </div>
    <p>
        <a class="btn btn-info" href="/SubDepartment/SubDepartmentInfo/@Model.Id">Назад към поднаправленията</a>
    </p>
</div>

SpecialtySelector/SpecialtySelector/Views/SubDepartment/SubDepartmentInfo.cshtml
@model IEnumerable<SpecialtySelector.Models.SubDepartment.SubDepartmentInfo>

@{
    ViewBag.Title = "Поднаправления";
}

@if (Model.Count() != 0)
{
    foreach (var sbDep in Model)
    {
        <div class="jumbotron text-center lead text-success mt-20">
            <h1 style="word-wrap: break-word">@sbDep.Name</h1>
            @if (sbDep.Description.Length < 200)
            {
                <h3 style="word-wrap: break-word">@sbDep.Description</h3>
            }
            else
            {
                <h3 style="word-wrap: break-word">@sbDep.Description.Substring(0, 200)...</h3>
            }
            <p>
                <a class="btn btn-info" href="\">Назад</a>
                <a class="btn btn-info" href="/SubDepartment/Details/@sbDep.Id">Виж повече</a>
                <a class="btn btn-info" href="/Specialty/SpecialtyInfo/@sbDep.Id">Виж специалности</a>
                @{if (Request.IsAuthenticated)
                  {
                      <div class="row">
                          <div class="col-md-6 text-right">
                              @using (Html.BeginForm("Delete", "SubDepartment", new { Id = sbDep.Id }, FormMethod.Post))
                              {
                                  <input class="btn btn-danger" type="submit" value="Изтриване" />
                              }
                          </div>
                          <div class="col-md-6 text-left">
                              @using (Html.BeginForm("Update", "SubDepartment", new { Id = sbDep.Id }, FormMethod.Get))
                              {
                                  <input class="btn btn-success" type="submit" value="Редактирай" />
                              }
                          </div>
                      </div>
                  }
                }
            </p>
        </div>
    }
}
else
{
    <h1 class="text-center lead">Все още няма добавени поднаправления къ съответното направление ....</h1>
}

SpecialtySelector/SpecialtySelector/Views/SubDepartment/Update.cshtml
@using SpecialtySelector.Data
@model SpecialtySelector.Models.SubDepartment.UpdateSubDepartment

@using (Html.BeginForm("Update", "SubDepartment", FormMethod.Post))
{
    <div class="row text-center">
        <p class="lead">Име на поднаправлението:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Name, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name, new { style = "width:500px;" })
        </div>
        <p class="lead">Описание на поднаправлението:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Description, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextAreaFor(m => m.Description, new { rows = "10", cols = "1200" })
        </div>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.DepartmentId, "", new { style = "color:red" })
        </div>
        <div>
            @{
                var options = new HashSet<SelectListItem>();
                var db = new SpecialtySelectorDbContext();
                var departments = db.Departments.ToList();
                foreach (var department in departments)
                {
                    options.Add(new SelectListItem { Text = $"{department.Name}", Value = $"{department.Id}", Selected = false });
                }
            }
            @Html.DropDownListFor(m => m.DepartmentId, options)
        </div>
        <div>
            <input class="btn btn-success" type="submit" value="Обнови" />
        </div>
    </div>
                }