SpecialtySelector/SpecialtySelector/Models/Subjects/AllSubjects.cs
namespace SpecialtySelector.Models.Subjects
{
    using SpecialtySelector.Data;
    using System.ComponentModel.DataAnnotations;

    public class AllSubjects
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(1000)]
        [MinLength(1)]
        public string Name { get; set; }

        public bool IsMandatory { get; set; }

        public int Credits { get; set; }

        [Required]
        public int Course { get; set; }

        public string AdminId { get; set; }

        public virtual User Admin { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/Subjects/CreateSubject.cs
namespace SpecialtySelector.Models.Subjects
{
    using SpecialtySelector.Data;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class CreateSubject
    {
        [Required(ErrorMessage = "Името трябва да бъде между 1-1000 символа !!!")]
        [Display(Name = "Име на предмет:")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Задължителен:")]
        public bool IsMandatory { get; set; }

        [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Кредити:")]
        public int Credits { get; set; }

        [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Курс:")]
        public int Course { get; set; }

        [Required(ErrorMessage = "Описанието трябва да бъде между 1-1600 символа !!!")]
        [Display(Name = "Кратко описание на предмета:")]
        public string Description { get; set; }

        public List<int> Specialty { get; set; }
        //fix
        public ICollection<Specialty> Specialties { get; set; }

        public List<int> Teacher { get; set; }
        //fix
        public ICollection<Teacher> Teachers { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/Subjects/SubjectInfo.cs
namespace SpecialtySelector.Models.Subjects
{
    using SpecialtySelector.Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class SubjectInfo
    {
        public ICollection<Teacher> Teachers { get; set; }
        public ICollection<Specialty> Specialties { get; set; }

        public int Id { get; set; }

        [Required]
        [MaxLength(1000)]
        [MinLength(1)]
        public string Name { get; set; }

        public bool IsMandatory { get; set; }

        public int Credits { get; set; }

        [Required]
        public int Course { get; set; }

        [StringLength(1600)]
        public string Description { get; set; }

        public DateTime? DeletedOn { get; set; }

        public string AdminId { get; set; }

        public virtual User Admin { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Models/Subjects/UpdateSubject.cs
namespace SpecialtySelector.Models.Subjects
{
    using SpecialtySelector.Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class UpdateSubject
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Името трябва да бъде между 1-1000 символа !!!")]
        [Display(Name = "Име на предмет:")]
        public string Name { get; set; }

       // [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Задължителен:")]
        public bool IsMandatory { get; set; }

        [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Кредити:")]
        public int Credits { get; set; }

        [Required(ErrorMessage = "Задължително поле")]
        [Display(Name = "Курс:")]
        public int Course { get; set; }

        [Required(ErrorMessage = "Описанието трябва да бъде между 1-1600 символа !!!")]
        [Display(Name = "Кратко описание на предмета:")]
        public string Description { get; set; }

        public DateTime? DeletedOn { get; set; }

        public List<int> Specialty { get; set; }

        public ICollection<Specialty> Specialties { get; set; }

        public List<int> Teacher { get; set; }

        public ICollection<Teacher> Teachers { get; set; }

        public string AdminId { get; set; }
    }
}

SpecialtySelector/SpecialtySelector/Controllers/SubjectController.cs
namespace SpecialtySelector.Controllers
{
    using Microsoft.AspNet.Identity;
    using SpecialtySelector.Data;
    using SpecialtySelector.Models.Subjects;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;

    public class SubjectController : Controller
    {
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            using (var db = new SpecialtySelectorDbContext())
            {
                var teachers = db.Teachers.ToList();
                var specialties = db.Specialties.ToList();
                
                ViewBag.Teachers = teachers;
                ViewBag.Specialties = specialties;

                return View();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateSubject createSubject)
        {
            if (createSubject != null && ModelState.IsValid)
            {
                using (var db = new SpecialtySelectorDbContext())
                {
                    var adminId = this.User.Identity.GetUserId();

                    var listOfTeachers = new List<Teacher>();
                    var listOfSpecialties = new List<Specialty>();

                    //FIX
                    if (createSubject.Teacher != null)
                    {
                        foreach (var teacher in createSubject.Teacher)
                        {
                            var currentTeacher = db.Teachers.FirstOrDefault(t => t.Id == teacher);
                            listOfTeachers.Add(currentTeacher);
                        }
                    }

                    //FIX
                    if (createSubject.Specialty != null)
                    {
                        foreach (var specialty in createSubject.Specialty)
                        {
                            var currentSpecialty = db.Specialties.FirstOrDefault(s => s.Id == specialty);
                            listOfSpecialties.Add(currentSpecialty);
                        }
                    }
                    
                    var subject = new Subject()
                    {
                        Name = createSubject.Name,
                        IsMandatory = createSubject.IsMandatory,
                        Credits = createSubject.Credits,
                        Course = createSubject.Course,
                        Description = createSubject.Description,
                        Specialties = listOfSpecialties,
                        Teachers = listOfTeachers,
                        AdminId = adminId
                    };

                    db.Subjects.Add(subject);
                    db.SaveChanges();

                    //FIX
                    return RedirectToAction("Details", new { id = subject.Id });
                }
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var teachers = db.Teachers.ToList();
                var specialties = db.Specialties.ToList();

                ViewBag.Teachers = teachers;
                ViewBag.Specialties = specialties;

                return View(createSubject);
            }            
        }

        public ActionResult AllSubjects()
        {
            using (var db = new SpecialtySelectorDbContext())
            {
                var subjects = db.Subjects
                    .Include(x => x.Teachers)
                    .Include(x => x.Specialties)
                    .Where(sp => sp.DeletedOn.Equals(null))
                    .Select(sp => new AllSubjects()
                    {
                        Id = sp.Id,
                        Name = sp.Name,
                        Credits = sp.Credits,
                        Course = sp.Course,
                        IsMandatory = sp.IsMandatory
                    })
                    .ToList();

                if (subjects == null)
                {
                    return HttpNotFound();
                }

                return View(subjects);
            }
        }

        public ActionResult Details(int? id)
        {
            //FIX
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subjects = db.Subjects
                    .Where(sp => sp.Id == id)
                    .Where(sp => sp.DeletedOn.Equals(null))
                    .Select(sp => new SubjectInfo
                    {
                        Id = sp.Id,
                        Name = sp.Name,
                        Description = sp.Description,
                        Specialties = sp.Specialties,
                        Teachers = sp.Teachers,
                        Course = sp.Course,
                        Credits = sp.Credits,
                        IsMandatory = sp.IsMandatory
                    })
                    .FirstOrDefault();

                if (subjects == null)
                {
                    return HttpNotFound();
                }

                return View(subjects);
            }
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subject = db.Subjects.Find(id);

                if (subject != null)
                {
                    subject.DeletedOn = DateTime.Now;
                }

                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult SubjectInfo(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subjects = db.Subjects
                    .Where(s => s.Id == id)
                    .Where(s => s.DeletedOn.Equals(null))
                    .Select(s => new SubjectInfo()
                    {
                        Id = s.Id,
                        Name = s.Name,
                        Description = s.Description,
                        Specialties = s.Specialties,
                        Teachers = s.Teachers,
                        Course = s.Course,
                        Credits = s.Credits,
                        IsMandatory = s.IsMandatory
                    })
                    .ToList();

                if (subjects == null)
                {
                    return HttpNotFound();
                }

                return View(subjects);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            using (var db = new SpecialtySelectorDbContext())
            {
                var subject = db.Subjects.Find(id);
                var adminId = this.User.Identity.GetUserId();

                if (subject == null)
                {
                    return HttpNotFound();
                }

                var updateSubjectModel = new UpdateSubject
                {
                    AdminId = adminId,
                    Id = subject.Id,
                    Name = subject.Name,
                    Description = subject.Description,
                    Credits = subject.Credits,
                    Course = subject.Course,
                    Teachers = subject.Teachers,
                    Specialties = subject.Specialties,
                    IsMandatory = subject.IsMandatory,
                    DeletedOn = subject.DeletedOn
                };

                return View(updateSubjectModel);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Update(UpdateSubject updateSubject)
        {
            if (ModelState.IsValid && updateSubject != null)
            {
                using (var db = new SpecialtySelectorDbContext())
                {
                    var subjects = db.Subjects.
                        Find(updateSubject.Id);

                    var adminId = this.User.Identity.GetUserId();

                    var listOfTeachers = new List<Teacher>();
                    var listOfSpecialties = new List<Specialty>();

                    if (updateSubject.Teacher != null)
                    {
                        foreach (var teacher in updateSubject.Teacher)
                        {
                            var currentTeacher = db.Teachers.FirstOrDefault(t => t.Id == teacher);
                            listOfTeachers.Add(currentTeacher);
                        }
                    }

                    if (updateSubject.Specialty != null)
                    {
                        foreach (var specialty in updateSubject.Specialty)
                        {
                            var currentSpecialty = db.Specialties.FirstOrDefault(s => s.Id == specialty);
                            listOfSpecialties.Add(currentSpecialty);
                        }
                    }

                    subjects.AdminId = adminId;
                    subjects.Name = updateSubject.Name;
                    subjects.Description = updateSubject.Description;
                    subjects.Course = updateSubject.Course;
                    subjects.Credits = updateSubject.Credits;
                    subjects.IsMandatory = updateSubject.IsMandatory;
                    subjects.DeletedOn = updateSubject.DeletedOn;
                    subjects.Specialties = listOfSpecialties;
                    subjects.Teachers = listOfTeachers;
                    subjects.Id = updateSubject.Id;

                    db.SaveChanges();
                }

SpecialtySelector/SpecialtySelector/Views/Subject/AllSubjects.cshtml
@using System.ComponentModel.DataAnnotations
@using System.Diagnostics.Eventing.Reader
@using System.Reflection
@model IEnumerable<SpecialtySelector.Models.Subjects.AllSubjects>

@foreach (var s in Model)
{

    <div class="jumbotron col-md-5 col-md-offset-1 text-center mt-30">
        <h2 class="lead text-info">
            Име на предмет: @s.Name
        </h2>
        <h3 class="lead">
            Курс: @s.Course / Кредити: @s.Credits
        </h3>
        <h3>
            Задължителен: @{
                 //FIX
                if (s.IsMandatory)
                {
                    <span>Да</span>
                }
                else
                {
                    <span>Не</span>
                }
            }
        </h3>
        @*@using (Html.BeginForm("Details", "Subject", new { Id = s.Id }, FormMethod.Get))
        {
            <input class="btn btn-success" type="submit" value="Виж повече" />
        }*@

        @{if (Request.IsAuthenticated)
            {
                <div class="row">
                    <div class="col-md-6 text-right">
                        @using (Html.BeginForm("Delete", "Subject", new { Id = s.Id }, FormMethod.Post))
                        {
                            <input class="btn btn-danger" type="submit" value="Изтриване" />
                        }
                    </div>
                    <div class="col-md-6 text-left">
                        @using (Html.BeginForm("Update", "Subject", new { Id = s.Id }, FormMethod.Get))
                        {
                            <input class="btn btn-success" type="submit" value="Редактирай" />
                        }
                    </div>
                </div>
            }
        }
    </div>

                }

SpecialtySelector/SpecialtySelector/Views/Subject/Create.cshtml
@model SpecialtySelector.Models.Subjects.CreateSubject

@{
    ViewBag.Title = "Създаване на предмет";
}

@using (Html.BeginForm("Create", "Subject", FormMethod.Post))
{
    <div class="text-center">
        <p class="lead">Име на предмет:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Name, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name, new { style = "width:500px;" })
        </div>
        <p class="lead">Задължителен:</p>
        @Html.CheckBoxFor(x => x.IsMandatory)

        <p class="lead">Кредити:</p>
        <div>
            @Html.TextBoxFor(m => m.Credits, new { style = "width:500px;" })
        </div>
        <p class="lead">Курс:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Course, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Course, new { style = "width:500px;" })
        </div>
        <p class="lead">Кратко описание на предмета:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Description, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextAreaFor(m => m.Description, new { rows = "7", cols = "1200" })
        </div>
        <p class="lead">Връзка със специалност:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Specialty, "", new { style = "color:red" })
        </div>

        <div>
            @{
                var specialtiesList = new HashSet<SelectListItem>();
                foreach (var sp in ViewBag.Specialties)
                {
                    specialtiesList.Add(new SelectListItem { Text = string.Format((string)"{0}", (object)sp.Name), Value = string.Format((string)"{0}", (object)sp.Id), Selected = false });
                }
            }
            @Html.ListBoxFor(m => m.Specialty, specialtiesList)
        </div>
        @*FIX*@ <p class="lead">Връзка с преподавател:</p>        
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Teacher, "", new { style = "color:red" })
        </div>
        <div>
            @{
                var teacherList = new HashSet<SelectListItem>();
                foreach (var t in ViewBag.Teachers)
                {
                    teacherList.Add(new SelectListItem { Text = string.Format((string)"{0}", (object)t.FirstName), Value = string.Format((string)"{0}", (object)t.Id), Selected = false });
                }
            }
            @Html.ListBoxFor(m => m.Teacher, teacherList)
        </div>

        <br />
        <div>
            <input type="submit" value="Добави предмет" />
        </div>
    </div>
                }

SpecialtySelector/SpecialtySelector/Views/Subject/Details.cshtml
@model SpecialtySelector.Models.Subjects.SubjectInfo
@using SpecialtySelector.Data.SpecialtySelectorEnums
@using System.Reflection
@using System.ComponentModel.DataAnnotations

@{
    ViewBag.Title = "Детайли";
}

<div class="jumbotron text-center lead">
    <div style="word-wrap: break-word">
        <h2>Име на предмета: @Model.Name</h2>
        <p>Кредити: @Model.Credits  Курс: @Model.Course</p>
        <p>
            Задължителен: @{
                    //FIX
                if (Model.IsMandatory)
                {
                    <span>Да</span>
                }
                else
                {
                    <span>Не</span>
                }
            }
        </p>
    </div>
    <div>
        @*FIX*@
        @if (Model.Specialties.Count != 0)
        {
            <div>Предметът се изучава в следните специалности:</div>
        {
                foreach (var specialty in Model.Specialties)
                {
                    var specialtyEqd = specialty.Eqd;
                    var displayEqd = specialtyEqd
                        .GetType()
                        .GetMember(specialty.Eqd.ToString())
                        .FirstOrDefault()
                        .GetCustomAttribute<DisplayAttribute>
                            ()
                            .GetName();

                            var SpecialtyFormOfEducation = specialty.FormOfEducation;
                            var displayFormOfEducation = SpecialtyFormOfEducation
                            .GetType()
                            .GetMember(specialty.FormOfEducation.ToString())
                            .FirstOrDefault()
                            .GetCustomAttribute<DisplayAttribute>
                                ()
                                .GetName();

                                <p>@specialty.Name (@displayEqd / @displayFormOfEducation)</p>
                                }
                                }
                                }

                    </div>

                    <div>
                        @*FIX*@
    @if (Model.Teachers.Count != 0)
    {
        <div>Преподаватели:</div>
        foreach(var teacher in Model.Teachers)
                                {
            var teacherAcademicTitle = teacher.AcademicTitle;
            var academicTitle = teacherAcademicTitle
                .GetType()
                .GetMember(teacher.AcademicTitle.ToString())
                .FirstOrDefault()
                .GetCustomAttribute<DisplayAttribute>
                    ()
                    .GetName();

                    var teacherDegree = teacher.Degree;
                    var degree = teacherDegree
                    .GetType()
                    .GetMember(teacher.Degree.ToString())
                    .FirstOrDefault()
                    .GetCustomAttribute<DisplayAttribute>
                        ()
                        .GetName();
                        <p>@academicTitle @degree @teacher.FirstName @teacher.LastName</p>
                        }
                        }

            </div>
                    <div>
                        <div class="lead">@Model.Description</div>
                    </div>


                </div>

SpecialtySelector/SpecialtySelector/Views/Subject/SubjectInfo.cshtml
@model IEnumerable<SpecialtySelector.Models.Subjects.SubjectInfo>

@{
    ViewBag.Title = "Детайли";
}

@if (Model.Count() != 0)
{
    foreach (var s in Model)
    {
        <div class="jumbotron text-center lead text-success mt-20">
            <h1 style="word-wrap: break-word">@s.Name</h1>
            @if (s.Description.Length < 200)
            {
                <h3 style="word-wrap: break-word">@s.Description</h3>
            }
            else
            {
                <h3 style="word-wrap: break-word">@s.Description.Substring(0, 200)...</h3>
            }
            <p>
                <a class="btn btn-info" href="\">Назад</a>
                <a class="btn btn-info" href="/Subject/Details/@s.Id">Виж повече</a>
                @{if (Request.IsAuthenticated)
                    {
                        <div class="row">
                            <div class="col-md-6 text-right">
                                @using (Html.BeginForm("Delete", "Subject", new { Id = s.Id }, FormMethod.Post))
                                {
                                    <input class="btn btn-danger" type="submit" value="Изтриване" />
                                }
                            </div>
                            <div class="col-md-6 text-left">
                                @using (Html.BeginForm("Update", "Subject", new { Id = s.Id }, FormMethod.Get))
                                {
                                    <input class="btn btn-success" type="submit" value="Редактирай" />
                                }
                            </div>
                        </div>
                    }
                }
            </p>
        </div>
                        }
                    }
                    else
                    {
                        <h1 class="text-center lead">Все още няма добавени предмети към съответния преподавател....</h1>
                    }

SpecialtySelector/SpecialtySelector/Views/Subject/Update.cshtml
@using SpecialtySelector.Data
@model SpecialtySelector.Models.Subjects.UpdateSubject

@{
    ViewBag.Title = "Редактиране";
}

@using (Html.BeginForm("Update", "Subject", FormMethod.Post))
{
    <div class="row text-center">
        <p class="lead">Име:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Name, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name, new { style = "width:500px;" })
        </div>
        <p class="lead">Задължителен:</p>
        @Html.CheckBoxFor(x => x.IsMandatory)
        <p class="lead">Кредити:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Credits, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Credits, new { style = "width:500px;" })
        </div>
        <p class="lead">Курс:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Course, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextBoxFor(m => m.Course, new { style = "width:500px;" })
        </div>
        <p class="lead">Описание:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Description, "", new { @style = "color:red" })
        </div>
        <div>
            @Html.TextAreaFor(m => m.Description, new { style = "width:500px;" })
        </div>
        
        <p class="lead">Връзка със специалност:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Specialty, "", new { style = "color:red" })
        </div>
        <div>
            @{
                var options = new HashSet<SelectListItem>();
                var db = new SpecialtySelectorDbContext();
                var specialties = db.Specialties.ToList();
                foreach (var specialty in specialties)
                {
                    options.Add(new SelectListItem { Text = $"{specialty.Name}", Value = $"{specialty.Id}", Selected = false });
                }
            }
            @Html.DropDownListFor(m => m.Specialties, options, new { @multiple = "true" })
        </div>
        <p class="lead">Връзка с преподавател:</p>
        <div class="lead">
            @Html.ValidationMessageFor(m => m.Teacher, "", new { style = "color:red" })
        </div>
        <div>
            @{
                var otherOptions = new HashSet<SelectListItem>();
                var database = new SpecialtySelectorDbContext();
                var teachers = db.Teachers.ToList();
                foreach (var teacher in teachers)
                {
                    otherOptions.Add(new SelectListItem { Text = $"{teacher.FirstName}", Value = $"{teacher.Id}", Selected = false });
                }
            }
            @Html.DropDownListFor(m => m.Specialties, otherOptions, new { @multiple = "true" })
        </div>
        <div>
            <input class="btn btn-success" type="submit" value="Обнови" />
        </div>
    </div>
                }